### ISSUE TITLE
[Feature Request] Toast 支持自定义组件

### ISSUE THREAD

**Issue by Mistrain-y-y** [vant-ui/vant#10659]
### 这个功能解决了什么问题？

更加灵活自定义 toast. 

### 你期望的 API 是什么样子的？

export declare type ToastOptions = {
    icon?: string;
    ...;
    component?: any;
};

**Comment by Alanscut** [comment]
个人感觉Toast是轻提示，不宜支持自定义组件，复杂场景可以使用Popup组件

**Comment by IamPlato** [comment]
> 



> 个人感觉Toast是轻提示，不宜支持自定义组件，复杂场景可以使用Popup组件

轻提示，也需要样式啊

**Comment by chenjiahan** [comment]
会在 4.0.0-rc.1 版本支持 Toast 自定义组件
