### ISSUE TITLE
[Bug Report] Popup 嵌套 Popover, Popover超出固定高度无法滚动

### ISSUE THREAD

**Issue by popring** [vant-ui/vant#10694]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-65h3ft?file=/src/App.vue:0-1005

### Vant 版本

3.4.6

### 描述一下你遇到的问题。

Popup 内容包含 Popover，Popover 设置固定高度时，Popover 无法滚动。

iOS下有问题，安卓下未测试。

经排查，将 useLockScroll 中的 onTouchMove 函数内容注释后，Popover 可正常滚动。

### 重现步骤

1. 展示 Popup
2. 展示 Popover
3. 滚动Popover内容

### 设备/浏览器

iOS

**Comment by popring** [comment]
目前是有迂回解决方案，但没有从根源解决问题：

可以通过设置 Popup 属性 lock-scroll="false" 解决该问题。但若页面超过一屏，在Popover 内容滚动至顶部或底部再滚动时会触发页面级别的滚动，与预期不符。

**Comment by chenjiahan** [comment]
是由于 Popover 内部对 touchstart 事件进行了 preventDefault 引起的，下个版本会修复此问题
