### ISSUE TITLE
[Bug Report] 按钮外层设置padding后外层容器的padding上下宽度不一致

### ISSUE THREAD

**Issue by extclp** [vant-ui/vant#10819]
### 重现链接

https://stackblitz.com/edit/vitejs-vite-nmtquh?file=src%2FApp.vue&terminal=dev

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

删掉.van-button__content:before样式后就会正常

### 重现步骤

.

### 设备/浏览器

macos, Firefox可以复现
chrome目前无法复现

**Comment by extclp** [comment]
@chenjiahan 没办法复现么

**Comment by chenjiahan** [comment]
还没下 Firefox，一般 Vant 不会对 PC 浏览器做特殊兼容处理

**Comment by extclp** [comment]
@chenjiahan 主要是iOS那边的, Firefox那边能复现而已

**Comment by JakeLaoyu** [comment]
button 是 inline-block 导致的空字符问题。 父元素设置一下 `font-size: 0;` 
取消父元素的 padding 上面会有一个红边

![uTools_1658668316566](https://user-images.githubusercontent.com/16181940/180648573-8d22d18a-62fd-4a90-8d83-b981f575f7bf.png)

**Comment by goo-yyh** [comment]
> 还没下 Firefox，一般 Vant 不会对 PC 浏览器做特殊兼容处理

![image](https://user-images.githubusercontent.com/45666106/180689546-7cbe026c-56cf-45c0-ba07-99d05a28625d.png)

chrome也能复现，高度小于34px时候就会出现空隙。

**Comment by chenjiahan** [comment]
这个伪类是有用的，用于解决 Icon 按钮的对齐问题，目前没什么合适的替代方案

可以试试 @JakeLaoyu 提供的方法
