### ISSUE TITLE
[Feature Request]   Collapse 想要一个 全部收起  全部展开

### ISSUE THREAD

**Issue by thgames908** [vant-ui/vant#10818]
### 这个功能解决了什么问题？

collapse想要一个 全部收起  全部展开 toggle的事件,  还有 默认全部展开  默认全部收起的props

### 你期望的 API 是什么样子的？

<van-collapse v-model="activeNames"  xxxx>  </van-collapse>

**Comment by chenjiahan** [comment]
checkbox-group 有提供 toggleAll 方法，可以直接使用。

另外 props 没有必要，直接修改 v-model 绑定的 value 即可。

**Comment by thgames908** [comment]
不是checkbox,      是Collapse,    Collapse没有toggleAll

**Comment by chenjiahan** [comment]
sorry 看错了
