### ISSUE TITLE
[Bug Report] van-uploader组件中OPPO、VIVO、1+手机无法进行图片多选

### ISSUE THREAD

**Issue by LinkerM** [vant-ui/vant#10847]
### 重现链接

https://notice.dbshopplus.com/#/

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

van-uploader组件中OPPO、VIVO、1+手机无法进行图片多选，只能一张一张传。而且也不支持在选择图片的时候进行预览。

### 重现步骤

1、在顶部已接中选择第一个项目；
2、点击底部执行；
3、点击拍照上传；
4、点击+号进行图片上传，部分机型图片不能多选。上传时也不支持预览。

### 设备/浏览器

OPPO、VIVO、1+手机

**Comment by chenjiahan** [comment]
参见：

![image](https://user-images.githubusercontent.com/7237365/181874388-105f3397-02f7-4615-8f39-a01a9cf6341e.png)
