### ISSUE TITLE
[Bug Report] 使用script setup没有类型

### ISSUE THREAD

**Issue by liyang1345** [vant-ui/vant#10848]
### 重现链接

https://gitee.com/liyangdamow/yg-ui

### Vant Cli 版本

4.0.3

### 描述一下你遇到的问题。

使用.vue模板语法，打包出来没有类型，请问如何解决
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/41931745/180759425-867bf2d2-e14c-485c-88d8-ab2957673304.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/41931745/180760364-481369f4-d1e8-4edc-88a7-97e68a9d571a.png">

### 重现步骤

使用vue模板语法开发即可复现

**Comment by chenjiahan** [comment]
这个和 @vant/cli 的实现没关系了，@vant/cli 是调用 tsc 来生成类型的，没有做特殊处理，最终生成的 .d.ts 内容取决于你的 TS 代码，建议自行调整下写法。
