### ISSUE TITLE
[Bug Report] Uploader用手机上传图片时，如果图片过多会无法上传成功。

### ISSUE THREAD

**Issue by LinkerM** [vant-ui/vant#10859]
### 重现链接

https://notice.dbshopplus.com/#/

### Vant 版本

3.4.5

### 描述一下你遇到的问题。

Uploader用手机上传图片时，如果图片过多，调用相册并选择完图片时无法正常走成功方法

https://user-images.githubusercontent.com/33533167/181667907-ee8d3b78-5fc7-47d8-8b1f-82dafecae83c.mp4

### 重现步骤

1、在顶部导航“已接中”选择第一个项目；
2、点击底部执行；
3、点击拍照上传；
4、如果施工工作项太多，或者手机有其他后台在执行的时候就会造成这种情况。

### 设备/浏览器

HUAWEIANA-AN00

**Comment by chenjiahan** [comment]
应该是图片太多，内存不够了，可以压缩图片试试

参见  https://vant-ui.github.io/vant/#/zh-CN/uploader#shang-chuan-tu-pian-shi-chu-xian-liu-lan-qi-shua-xin-huo-qia-dun-xian-xiang

![image](https://user-images.githubusercontent.com/7237365/181872844-5a23a8ea-9858-4a6f-9797-db02a3e92fc6.png)
