### ISSUE TITLE
使用dialog 组件化的方式引用

### ISSUE THREAD

**Issue by hhcol620** [vant-ui/vant#10856]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-rpfmoc?file=/src/App.vue

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

dialog 组件化调用不支持 vue3 里面的script setup

### 重现步骤

script setup中无法注册组件

**Comment by chenjiahan** [comment]
看了下重现链接里的代码可以正常运行。

如果在 setup 里使用，可以参考：

![image](https://user-images.githubusercontent.com/7237365/181875284-13dc3b21-d202-4734-a8d5-a4f21b8fc8f7.png)
