### ISSUE TITLE
[Bug Report]Vite unlugin-vue-components 自动加载工具，导致 Dialog 组件自动加载然后失控

### ISSUE THREAD

**Issue by landsu** [vant-ui/vant#10855]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-5ksgxt

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

开启 unlugin-vue-components 后，Dialog 的函数调用，组件调用都失灵，页面加载后，会自动弹出，然后点击事件就无法控制它再次出现了。

关闭 unlugin-vue-components 插件，换手动引入，一切正常。关键是不想用手动引入。

引入了 import 'vant/es/dialog/style'; Dialog 样式，所以样式没有问题，但这不受控制的自动弹出，然后失控是怎么解决呢？

vant: ^3.5.2
vite: ^3.0.0
vue: ^3.2.37
unlugin-vue-components: ^0.21.2

### 重现步骤

1.  在Vite中安装配置 unlugin-vue-components 插件
2.  在组件中使用函数引入或组件引入 Dialog
3.  预览页面
4.  页面加载后，Dialog 自动弹出
5.  用函数或组件 v-model 无法控制此组件，彻底失控

### 设备/浏览器

Windows 10 21H1 / Chrome 103.0.5060.134

**Comment by Alanscut** [comment]
Dialog 是一个函数而非组件，需要手动注册下 Dialog.Component
![image](https://user-images.githubusercontent.com/21104054/181409978-58b33630-ab46-4c92-95d5-c1930f38ad54.png)

**Comment by landsu** [comment]
> Dialog 是一个函数而非组件，需要手动注册下 Dialog.Component
> ![image](https://user-images.githubusercontent.com/21104054/181409978-58b33630-ab46-4c92-95d5-c1930f38ad54.png)

有函数，有组件，两个都有。不管是哪个，也不管是全局引用，还是局部引用都试了。只要自动按需引用插件开着，就会出现上面描述的问题。

**Comment by lianghw** [comment]
表示遇到同样问题，然后在vant-demo中vite下测试 ，增加了如下代码

<img width="737" alt="图片" src="https://user-images.githubusercontent.com/29350837/181420447-b1ab218f-bb69-405f-bfc0-aef00c102ac9.png">

﻿
![图片](https://user-images.githubusercontent.com/29350837/181420959-6f2d38ec-03c2-4e44-81f6-dd68d25fbb1e.png)


运行工程后直接弹出Dialog弹窗，并抛出异常，因为自定义的信息没有展示，添加内容为官方文档示例

![图片](https://user-images.githubusercontent.com/29350837/181420705-8bc2d705-937c-40b2-8bb8-b4efe344acdd.png)

**Comment by Alanscut** [comment]
应该是 unplugin-vue-components 没有兼容默认导出是函数这种场景，可以加上：
```
<script setup>
import 'vant/es/dialog/style';
import { Dialog } from 'vant';
const VanDialog = Dialog.Component;
</script>
```

**Comment by landsu** [comment]
> 应该是 unplugin-vue-components 没有兼容默认导出是函数这种场景，可以加上：
> 
> ```
> <script setup>
> import 'vant/es/dialog/style';
> import { Dialog } from 'vant';
> const VanDialog = Dialog.Component;
> </script>
> ```

经过一番痛苦的折腾，最终发现原因是，我没有用 setup 语法糖，换成 steup 方式就可以了，必须是<script setup></script>。在 export default 中用setup() + return 都不行！

1. <script> 换成 <script setup>
2. 注册 ref，computed，watch，生命周期钩子等等
3. data() 里变量都重新定义，需要响应的就用ref()
4. methods 改成 setup 方式
5. computed，watch，生命周期钩子也要改成 setup 方式
6. 一大推的 this. 全去掉，把变量前面的 this. 去掉，后面加上 .value （怎么还多了一个字母呢？）
7. 引入 Dialog 函数和样式
8. <template> 中随便找个地方插入 <van-dialog /> 标签
9.  函数中用 Dialog.alert(), Dialog.close() 控制开关

小白一个，从前也没用过 setup 一路各种查资料，都快给我整崩溃了。
还是自动按需引入香啊~~~
感觉 setup 比较灵活，想怎么写就这么写。以后就用 setup 了。

**Comment by lianghw** [comment]
> 



> > 应该是 unplugin-vue-components 没有兼容默认导出是函数这种场景，可以加上：
> > ```
> > <script setup>
> > import 'vant/es/dialog/style';
> > import { Dialog } from 'vant';
> > const VanDialog = Dialog.Component;
> > </script>
> > ```
> 
> 经过一番痛苦的折腾，最终发现原因是，我没有用 setup 语法糖，换成 steup 方式就可以了，必须是<script setup></script>。在 export default 中用setup() + return 都不行！
> 
>     1. <script> 换成 <script setup>
> 
>     2. 注册 ref，computed，watch，生命周期钩子等等
> 
>     3. data() 里变量都重新定义，需要响应的就用ref()
> 
>     4. methods 改成 setup 方式
> 
>     5. computed，watch，生命周期钩子也要改成 setup 方式
> 
>     6. 一大推的 this. 全去掉，把变量前面的 this. 去掉，后面加上 .value （怎么还多了一个字母呢？）
> 
>     7. 引入 Dialog 函数和样式
> 
>     8. <template> 中随便找个地方插入 <van-dialog /> 标签
> 
>     9. 函数中用 Dialog.alert(), Dialog.close() 控制开关
> 
> 
> 小白一个，从前也没用过 setup 一路各种查资料，都快给我整崩溃了。 还是自动按需引入香啊~~~ 感觉 setup 比较灵活，想怎么写就这么写。以后就用 setup 了。

貌似还是bug... 不然这永远是个痛，而且按照官方文档去写，必然会出现这种问题 。 还是需要去修复的，总不能连 setup(){ return }  都不能用吧 。
