### ISSUE TITLE
[Bug Report] Vue 2.7 Toast 单例全局引用刷新页面第一次才能显示，后面再次调用不显示

### ISSUE THREAD

**Issue by xrwben** [vant-ui/vant#10863]
### 重现链接

内网项目

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

**问题：打包后a页面打开请求接口显示Toast，进入b页面然后后退接口有请求，但是Toast不再显示（本地开发可以）**

全量引入使用
![图片](https://user-images.githubusercontent.com/22901939/181754123-7572dfcc-cd9c-4211-aa3a-4b0eb2122f4c.png)

a页面第一次显示层级后后面就似乎没有再调用过了 一直保持这个dom
![图片](https://user-images.githubusercontent.com/22901939/181753322-b1a09c82-4635-4713-9311-b8fed0711dd1.png)

其它页面使用this.$toast.loading()调用都不再显示，除非刷新页面

如果使用this.$toast.clear(true)清理，Toast生成的dom会越来越多
![图片](https://user-images.githubusercontent.com/22901939/181764998-dfccadde-1b93-4ecf-b598-0fad3033d63f.png)

### 重现步骤

进入a页面显示 -> b页面不显示Toast -> 回退到a页面也不显示Toast

### 设备/浏览器

移动端打包后都有这个问题

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/181872576-3c988af6-77ba-4fed-8cea-f170727d00d8.png)

**Comment by york17** [comment]
确实有这个问题，新基建一个项目，也出现了。

**Comment by york17** [comment]
> ### 重现链接
> 内网项目
> 
> ### Vant 版本
> 2.12.48
> 
> ### 描述一下你遇到的问题。
> **问题：打包后a页面打开请求接口显示Toast，进入b页面然后后退接口有请求，但是Toast不再显示（本地开发可以）**
> 
> 全量引入使用 ![图片](https://user-images.githubusercontent.com/22901939/181754123-7572dfcc-cd9c-4211-aa3a-4b0eb2122f4c.png)
> 
> a页面第一次显示层级后后面就似乎没有再调用过了 一直保持这个dom ![图片](https://user-images.githubusercontent.com/22901939/181753322-b1a09c82-4635-4713-9311-b8fed0711dd1.png)
> 
> 其它页面使用this.$toast.loading()调用都不再显示，除非刷新页面
> 
> 如果使用this.$toast.clear(true)清理，Toast生成的dom会越来越多 ![图片](https://user-images.githubusercontent.com/22901939/181764998-dfccadde-1b93-4ecf-b598-0fad3033d63f.png)
> 
> ### 重现步骤
> 进入a页面显示 -> b页面不显示Toast -> 回退到a页面也不显示Toast
> 
> ### 设备/浏览器
> 移动端打包后都有这个问题

降低你的vue版本，我这边也是出现你这边问题，排查了好久，发现是vue的问题，我们新创建的工程，默认是vue的版本是2.7.8，我这边降级到2.6.11版本，就可以正常使用。具体什么问题，还未排查。可以先优化这么处理。
@chenjiahan 您这边有时间的话，可以帮忙排查下具体问题，如果是因为vue2最新版本问题的话，还请在文档中备注；
谢谢。

**Comment by chenjiahan** [comment]
好的，后续会看下这个问题

**Comment by chenjiahan** [comment]
最好给个 codesandbox 复现链接哈

**Comment by york17** [comment]
> 最好给个 codesandbox 复现链接哈

**codesandbox.io/s/misty-dust-6q7mpo**  链接有了。

感谢提供vant这个这么好用的组件库；

**Comment by ChangeZhang** [comment]
same issue

**Comment by york17** [comment]
> same issue

Reduce the vue version in the project, you can use version 2.6.14;

**Comment by chenjiahan** [comment]
看了下应该是 Vue v2.7 的 bug，通过 Vue.extend 创建的元素，在页面切换后就无法正常渲染了

目前可以先通过锁定 Vue 版本来解决，后续我们看下怎么处理

**Comment by xiaozhanghui** [comment]
这个bug，vue修复了，升级vue就行了
