### ISSUE TITLE
iPhone使用上传组件，capture=camera时，拍完照上传成功不能自动保存到手机相册吗？

### ISSUE THREAD

**Issue by huangbinfa** [vant-ui/vant#10862]
### 重现链接

无

### Vant 版本

2.11.0

### 描述一下你遇到的问题。

iphone手机使用上传组件，拍照上传图片，拍完后组件有图片，但是手机本地相册没有图片？

### 重现步骤

iPhone手机，企业微信-工作台-web应用
点击上传组件，调用相机，拍照完成，组件已经有图片，但是本地相册没有图片
企业微信聊天拍照可以正常保存到手机相册

### 设备/浏览器

iPhone

**Comment by chenjiahan** [comment]
这个是系统自身的行为，和组件库没关系喔，组件库控制不了这个
