### ISSUE TITLE
Vant cli里面能引入elementui吗

### ISSUE THREAD

**Issue by ljj501** [vant-ui/vant#10861]
### 这个功能解决了什么问题？

我想在vant cli里面使用element ui，却发现引入之后报错，Vant cli支持这样操作吗

### 你期望的 API 是什么样子的？

vant cli能引入element ui

**Comment by chenjiahan** [comment]
可以的，如果遇到问题可以提供一个复现链接看下

**Comment by Jean-Jacques-Nuoan** [comment]
vant cli引入element ui有示例吗
