### ISSUE TITLE
vant cli创建的项目中，引入elementui 报错

### ISSUE THREAD

**Issue by ljj501** [vant-ui/vant#10871]
### 重现链接

https://github.com/ljj501/personal.git

### Vant Cli 版本

2.11.11

### 描述一下你遇到的问题。

引入elmentui 至页面中，有报错

### 重现步骤

1.克隆仓库
2.切换到master分支
3.yarn install
4.yarn dev
5.打开浏览器调试
6.打开ifly-split/index.vue 在页面中引入elementui
7.查看控制台报错
![image](https://user-images.githubusercontent.com/32152657/182057162-e8a7fa55-a7c4-4c6c-9e21-579738bd5ba2.png)

**Comment by chenjiahan** [comment]
Vant Cli 2.x 版本已经不维护了哈，遇到问题可以自行修复，可以提 PR 到 2.x 分支
