### ISSUE TITLE
[Bug Report] Component van-button is missing template or render function.

### ISSUE THREAD

**Issue by hqwlkj** [vant-ui/vant#10873]
### 重现链接

xx

### Vant 版本

4.0.0-beta.0

### 描述一下你遇到的问题。

nuxt3  + vant 进行打包部署后发布了报` [Vue warn]: Component van-button is missing template or render function.` 错误提示。

### 重现步骤

在nuxt3的插件中这样全局引入 vant 的组件

<img width="983" alt="image" src="https://user-images.githubusercontent.com/12181423/182088723-53ef337d-17d4-4c98-9e02-9c0a8eed77e0.png">

<img width="846" alt="image" src="https://user-images.githubusercontent.com/12181423/182088985-a88c75a3-5e0d-4956-8328-fa59033aa5de.png">

**Comment by qyn980427** [comment]
我在build之后也碰到了类似的问题

**Comment by qyn980427** [comment]
[Vue warn]: Component van-tabbar-item is missing template or render function.

**Comment by chenjiahan** [comment]
统一在这个 issue 中跟进吧：https://github.com/vant-ui/vant/issues/10877
