### ISSUE TITLE
[Bug Report] 在nuxt3中使用vant,打包后运行异常

### ISSUE THREAD

**Issue by qyn980427** [vant-ui/vant#10877]
### 重现链接

https://stackblitz.com/edit/nuxt-starter-txwyvc?file=plugins%2Fvant.ts,pages%2Findex.vue,package.json

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

在nuxt3中使用vant，目前项目刚开始，使用vant组件不是特别多，在开发环境中没什么异常，打包后出现异常
暂时发现的问题：
1. @vant/touch-emulator doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
2. 类似于 [Vue warn]: Component van-tabbar-item is missing template or render function.这样的报错，好几个组件都有
3. 使用Tabbar之后，TypeError: Cannot read properties of null (reading 'proxy')，导致nuxt出现500

![image](https://user-images.githubusercontent.com/65841456/182351841-78c6bd86-6640-434a-8889-587971b2c281.png)
![image](https://user-images.githubusercontent.com/65841456/182351906-138c1231-2cfd-43fe-9ede-5f132771dddf.png)
![image](https://user-images.githubusercontent.com/65841456/182352028-e96c02c1-a45e-4bdd-ad60-4259fb993f28.png)

### 重现步骤

如上述链接锁提供demo
1.npm run build 
2.npm run preview
3.访问
4.访问后控制台出现异常

### 设备/浏览器

很好复现

**Comment by chenjiahan** [comment]
@vant/touch-emulator 的问题已发布 1.4.0 版本修复

**Comment by hqwlkj** [comment]
@chenjiahan  这个问题 https://github.com/vant-ui/vant/issues/10873  是需要自己在项目中添加 @vant/touch-emulator@1.4.0的依赖吗？

**Comment by qyn980427** [comment]
您好，vant/touch-emulator这个插件我看已经修复 
我目前在nuxt3项目中所使用的vant组件非常有限，所以我不确定除了那几个组件之外的其他组件是否有类似问题
我现在有两个疑问：
1.在bug修复之前，是否有中转方案可以解决这个问题？
2.现在在nuxt3项目中，vant4.x可以投入使用吗？

**Comment by chenjiahan** [comment]
vant 4 是挺稳定了，不过 nuxt 3 还不是很稳定，报的问题也莫名其妙的，暂时没有头绪

**Comment by chenjiahan** [comment]
感兴趣的话可以深入研究下原因，给 vant 提个 PR~

**Comment by qyn980427** [comment]
您的意思是vant3.x目前在nuxt3里面，这个issure提到的这类型问题还没有头绪解决是吗？

**Comment by hqwlkj** [comment]
vant4  + nuxt3 目前也会存在这样的问题

**Comment by chenjiahan** [comment]
> 这个issure提到的这类型问题还没有头绪解决是吗？

嗯，复杂的问题还没时间看

**Comment by chenjiahan** [comment]
nuxt 3 还没正式发布，功能不算稳定

**Comment by hqwlkj** [comment]
@chenjiahan  

https://github.com/nuxt/framework/issues/6761 

nuxt3 的开发人员回复的，麻烦你们看一如何处理

**Comment by chenjiahan** [comment]
> nuxt3 的开发人员回复的，麻烦你们看一如何处理

这个 issue 里已经提供了很明确的描述了吧，本质上与 Vant 无关的，只要 external 了 Vue 的 library 都会遇到这个问题。

> You can track the root issue at https://github.com/nuxt/framework/issues/4084.

> You can add /vant/ to your build.transpile or enable experimental.externalVue for now:

**Comment by hqwlkj** [comment]
> > nuxt3 的开发人员回复的，麻烦你们看一如何处理
> 
> 这个 issue 里已经提供了很明确的描述了吧，本质上与 Vant 无关的，只要 external 了 Vue 的 library 都会遇到这个问题。
> 
> > You can track the root issue at [nuxt/framework#4084](https://github.com/nuxt/framework/issues/4084).
> 
> > You can add /vant/ to your build.transpile or enable experimental.externalVue for now:

赞
