### ISSUE TITLE
v2.x 支持的多语言远远不及v4版本

### ISSUE THREAD

**Issue by yehoan** [vant-ui/vant#10874]
### 这个功能解决了什么问题？

希望v2.x 能和v4 支持的多语言保持同步

### 你期望的 API 是什么样子的？

希望v2.x 能和v4 支持的多语言保持同步

**Comment by yehoan** [comment]
因为公司项目体量以及业务庞大 短期内很难升级到版本  请问怎么处理 多语言问题  比如印尼语 就没看见支持... 但是v4  v3 早就支持了 目前较难升级 请问怎么处理 谢谢

**Comment by yehoan** [comment]
能不能同步到v2

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/182099260-ab6c3823-c198-4117-88e4-0d87255ff026.png)

**Comment by yehoan** [comment]
我知道维护成本会降低  主要这个多语言 希望能不能同步一下 ..

**Comment by chenjiahan** [comment]
你可以提 PR 来贡献哈，我们会进行代码合并和发布
