### ISSUE TITLE
cdn引入van-tabs引入异常

### ISSUE THREAD

**Issue by zhanghan-cdns** [vant-ui/vant#10878]
### 重现链接

https://codesandbox.io/s/distracted-wu-bt8ygf?file=/index.html

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

van-tabs组件引入无效   会报错Uncaught ReferenceError: process is not defined

### 重现步骤

正常cdn的方式引入

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
应该是升级 vite 3 导致的问题，可以先锁定 CDN 使用的版本到 3.5.2

https://fastly.jsdelivr.net/npm/vant@3.5.2/lib/vant.min.js

我们尽快修复下

**Comment by chenjiahan** [comment]
已在 3.5.4 版本修复
