### ISSUE TITLE
[Feature Request] Slide在多语言(阿拉伯语/希伯来语)场景下的rtl布局的适配情况

### ISSUE THREAD

**Issue by LLLiuRX** [vant-ui/vant#10872]
### 这个功能解决了什么问题？

想请教下如何适配rtl布局下 slide滑块的左右滑动

### 你期望的 API 是什么样子的？

是否能通过属性支持？

**Comment by chenjiahan** [comment]
目前 Vant 的组件是没有做 rtl 适配的，后续会评估下

**Comment by chenjiahan** [comment]
可以使用 Slider 在 v3.2.1 版本新增的 reverse 属性来适配 rtl 布局
