### ISSUE TITLE
Nuxt Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by china-Zzzz** [vant-ui/vant#10883]
### 重现链接

无

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

nuxt框架通过cdn的方式引入vant使用ssr渲染的时候浏览器报错DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method

### 重现步骤

1、nuxt项目启动服务
2、访问启动服务

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/183242971-bc9056d1-7ca2-48ad-93a8-fd60c8afb158.png)
