### ISSUE TITLE
省市区选择地区缺少反馈，共346条

### ISSUE THREAD

**Issue by wsqrin** [vant-ui/vant#10885]
### Reproduction Link

https://github.com/vant-ui/vant/blob/dev/packages/vant-area-data/src/index.ts

### Vant Version

3.5.3

### Describe the Bug

341400:'巢湖市'
371200:'莱芜市'
522200:'铜仁地区'
522400:'毕节地区'
542100:'昌都地区'
542200:'山南地区'
542300:'日喀则地区'
542400:'那曲地区'
542600:'林芝地区'
632100:'海东地区'
652100:'吐鲁番地区'
652200:'哈密地区'
------------------------------------
110103:'崇文区'
110104:'宣武区'
110228:'密云县'
110229:'延庆县'
120107:'塘沽区'
120108:'汉沽区'
120109:'大港区'
120221:'宁河县'
120223:'静海县'
120225:'蓟县'
130103:'桥东区'
130124:'栾城县'
130182:'藁城市'
130185:'鹿泉市'
130223:'滦县'
130230:'唐海县'
130323:'抚宁县'
130421:'邯郸县'
130428:'肥乡县'
130429:'永年县'
130521:'邢台县'
130526:'任县'
130527:'南和县'
130603:'北市区'
130604:'南市区'
130621:'满城县'
130622:'清苑县'
130625:'徐水县'
130721:'宣化县'
130729:'万全县'
130733:'崇礼县'
130823:'平泉县'
131181:'冀州市'
140202:'城区'
140203:'矿区'
140211:'南郊区'
140227:'大同县'
140402:'城区'
140411:'郊区'
140421:'长治县'
140424:'屯留县'
140481:'潞城市'
140501:'晋城市市辖区'
140624:'怀仁县'
140726:'太谷县'
210122:'辽中县'
210282:'普兰店市'
211121:'大洼县'
220181:'九台市'
220724:'扶余县'
230182:'双城市'
230702:'伊春区'
230703:'南岔区'
230704:'友好区'
230705:'西林区'
230706:'翠峦区'
230707:'新青区'
230708:'美溪区'
230709:'金山屯区'
230710:'五营区'
230711:'乌马河区'
230712:'汤旺河区'
230713:'带岭区'
230714:'乌伊岭区'
230715:'红星区'
230716:'上甘岭区'
230833:'抚远县'
231024:'东宁县'
231121:'嫩江县'
232702:'松岭区'
232703:'新林区'
232704:'呼中区'
232723:'漠河县'
310103:'卢湾区'
310108:'闸北区'
310230:'崇明县'
320103:'白下区'
320107:'下关区'
320124:'溧水县'
320125:'高淳县'
320202:'崇安区'
320203:'南长区'
320204:'北塘区'
320304:'九里区'
320323:'铜山县'
320405:'戚墅堰区'
320482:'金坛市'
320502:'沧浪区'
320503:'平江区'
320504:'金阊区'
320584:'吴江市'
320621:'海安县'
320705:'新浦区'
320721:'赣榆县'
320802:'清河区'
320811:'清浦区'
320829:'洪泽县'
320982:'大丰市'
321011:'维扬区'
321088:'江都市'
321284:'姜堰市'
330103:'下城区'
330104:'江干区'
330183:'富阳市'
330185:'临安市'
330204:'江东区'
330283:'奉化市'
330322:'洞头县'
330621:'绍兴县'
330682:'上虞市'
331021:'玉环县'
340502:'金家庄区'
340702:'铜官山区'
340703:'狮子山区'
340721:'铜陵县'
340823:'枞阳县'
340824:'潜山县'
341402:'居巢区'
341421:'庐江县'
341422:'无为县'
341423:'含山县'
341424:'和县'
341521:'寿县'
341822:'广德县'
350182:'长乐市'
350784:'建阳市'
350822:'永定县'
360105:'湾里区'
360122:'新建县'
360421:'九江县'
360427:'星子县'
360622:'余江县'
360721:'赣县'
360782:'南康市'
361029:'东乡县'
361121:'上饶县'
361122:'广丰县'
370125:'济阳县'
370181:'章丘市'
370205:'四方区'
370282:'即墨市'
370284:'胶南市'
370521:'垦利县'
370802:'市中区'
370882:'兖州市'
371081:'文登市'
371202:'莱城区'
371203:'钢城区'
371421:'陵县'
371523:'茌平县'
371624:'沾化县'
371626:'邹平县'
371727:'定陶县'
410211:'金明区'
410224:'开封县'
410728:'长垣县'
411023:'许昌县'
411222:'陕县'
411626:'淮阳县'
420321:'郧县'
420821:'京山县'
430122:'望城县'
430124:'宁乡县'
430221:'株洲县'
430521:'邵东县'
440116:'萝岗区'
440183:'增城市'
440184:'从化市'
440903:'茂港区'
440923:'电白县'
441283:'高要市'
441421:'梅县'
441723:'阳东县'
441827:'清新县'
445121:'潮安县'
445221:'揭东县'
445323:'云安县'
450122:'武鸣县'
450221:'柳江县'
450322:'临桂县'
450331:'荔蒲县'
450404:'蝶山区'
451021:'田阳县'
451023:'平果县'
451025:'靖西县'
451119:'平桂管理区'
451281:'宜州市'
469003:'儋州市'
469031:'西沙群岛'
469032:'南沙群岛'
469033:'中沙群岛的岛礁及其海域'
500222:'綦江县'
500223:'潼南县'
500224:'铜梁县'
500225:'大足县'
500226:'荣昌县'
500227:'璧山县'
500228:'梁平县'
500232:'武隆县'
500234:'开县'
510122:'双流县'
510124:'郫县'
510626:'罗江县'
510724:'安县'
510922:'射洪县'
511028:'隆昌县'
511422:'彭山县'
511521:'宜宾县'
511522:'南溪县'
511721:'达县'
511821:'名山县'
512081:'简阳市'
513229:'马尔康县'
513321:'康定县'
520114:'小河区'
520222:'盘县'
520321:'遵义县'
520421:'平坝县'
522201:'铜仁市'
522222:'江口县'
522223:'玉屏侗族自治县'
522224:'石阡县'
522225:'思南县'
522226:'印江土家族苗族自治县'
522227:'德江县'
522228:'沿河土家族自治县'
522229:'松桃苗族自治县'
522230:'万山特区'
522322:'兴仁县'
522401:'毕节市'
522422:'大方县'
522423:'黔西县'
522424:'金沙县'
522425:'织金县'
522426:'纳雍县'
522427:'威宁彝族回族苗族自治县'
522428:'赫章县'
530121:'呈贡县'
530122:'晋宁县'
530321:'马龙县'
530328:'沾益县'
530421:'江川县'
530422:'澄江县'
530522:'腾冲县'
530630:'水富县'
532526:'弥勒县'
532621:'文山县'
533321:'泸水县'
533421:'香格里拉县'
540125:'堆龙德庆县'
540126:'达孜县'
542121:'昌都县'
542122:'江达县'
542123:'贡觉县'
542124:'类乌齐县'
542125:'丁青县'
542126:'察雅县'
542127:'八宿县'
542128:'左贡县'
542129:'芒康县'
542132:'洛隆县'
542133:'边坝县'
542221:'乃东县'
542222:'扎朗县'
542223:'贡嘎县'
542224:'桑日县'
542225:'琼结县'
542226:'曲松县'
542227:'措美县'
542228:'洛扎县'
542229:'加查县'
542231:'隆子县'
542232:'错那县'
542233:'浪卡子县'
542301:'日喀则市'
542322:'南木林县'
542323:'江孜县'
542324:'定日县'
542325:'萨迦县'
542326:'拉孜县'
542327:'昂仁县'
542328:'谢通门县'
542329:'白朗县'
542330:'仁布县'
542331:'康马县'
542332:'定结县'
542333:'仲巴县'
542334:'亚东县'
542335:'吉隆县'
542336:'聂拉木县'
542337:'萨嘎县'
542338:'岗巴县'
542421:'那曲县'
542422:'嘉黎县'
542423:'比如县'
542424:'聂荣县'
542425:'安多县'
542426:'申扎县'
542427:'索县'
542428:'班戈县'
542429:'巴青县'
542430:'尼玛县'
542621:'林芝县'
542622:'工布江达县'
542623:'米林县'
542624:'墨脱县'
542625:'波密县'
542626:'察隅县'
542627:'朗县'
610125:'户县'
610126:'高陵县'
610427:'彬县'
610521:'华县'
610623:'子长县'
610624:'安塞县'
610721:'南郑县'
610821:'神木县'
610823:'横山县'
620824:'华亭县'
630122:'湟中县'
632121:'平安县'
632122:'民和回族土族自治县'
632123:'乐都县'
632126:'互助土族自治县'
632127:'化隆回族自治县'
632128:'循化撒拉族自治县'
632721:'玉树县'
652101:'吐鲁番市'
652122:'鄯善县'
652123:'托克逊县'
652201:'哈密市'
652222:'巴里坤哈萨克自治县'
652223:'伊吾县'
652923:'库车县'

### Reproduce Steps

自己程序内对比缺少的地址

### Device / Browser

PC

**Comment by chenjiahan** [comment]
你的数据不一定是最新的，举个例子，你上面贴了 330103:'下城区' 和 330104:'江干区'，这俩都已经被撤销了

> 2021年3月11日，浙江省人民政府发布《关于调整杭州市部分行政区划的通知》。撤销杭州市上城区、江干区

如果觉得哪条数据有问题，可以查询最新的官网数据来确认，然后提 PR 给 vant 更新数据
