### ISSUE TITLE
[Bug Report] tabs、pullrefresh、list组件一起用的时候会出现重复加载数据的情况

### ISSUE THREAD

**Issue by garfieldwow** [vant-ui/vant#10882]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-t4ih7b?file=/src/Anchor.vue

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

下拉刷新的时候会重复加载好几次数据,tabs、pullrefresh、list组件三个一起用的时候会出现

### 重现步骤

随便选择一个tab页下拉刷新，会走好几遍数据加载方法，没看懂这个问题是怎么出现的....

### 设备/浏览器

谷歌浏览器改成手机调试模式

**Comment by chenjiahan** [comment]
因为你在 pageNo === 1 的时候没做任何数据加载操作，列表为空，所以继续触发了第二次加载，这个是符合预期的
