### ISSUE TITLE
vue3，Typescript使用vant全局组件可用，辅助函数不可用？

### ISSUE THREAD

**Issue by chuangdao** [vant-ui/vant#10895]
### 重现链接

https://rvsfn7.csb.app

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

引入Toast这种全局注册组件 是正常使用的
import { Toast, Dialog   } from 'vant'

但如果引入 vant提供了一系列辅助函数,就不能使用
import { showToast, showDialog  } from 'vant';

提示：
import showToast
模块 ""vant"" 没有导出的成员 "showToast"。你是想改用 "import showToastfrom "vant"" 吗? ts(2614)
![image](https://user-images.githubusercontent.com/24773738/183551561-97833a5e-e969-4916-ab26-ee7210caac89.png)
麻烦指导一下，谢谢

### 重现步骤

如图

### 设备/浏览器

谷歌

**Comment by chenjiahan** [comment]
vant 版本要升级到 4.0.0-beta.0

**Comment by chuangdao** [comment]
vant 版本是 4.0.0-beta.0

**Comment by chenjiahan** [comment]
那你更新下复现链接
