### ISSUE TITLE
[Bug Report] 第一次打开时间区间选择器时报错getFullYear undefined

### ISSUE THREAD

**Issue by caiheqiang** [vant-ui/vant#10893]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/calendar

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/45744849/183364203-3eff3b7c-a498-45c2-8949-7f24c11f0903.png">

### 重现步骤

第一次打开时间区间选择器时报错getFullYear undefined
按照文档给了所有必须填的参数
当v-model.show第一次为true时，控制台报错如上图所示。
然后我到官方文档中打开发现了同样的问题
第一次打开时间区间选择器会报同样的错误

### 设备/浏览器

MacBook Pro Google Chrome 版本103.0.5060.53

**Comment by chenjiahan** [comment]
感谢反馈，我们排查下
