### ISSUE TITLE
[Feature Request] unplugin-vue-components 文档优化

### ISSUE THREAD

**Issue by zhoujiankang** [vant-ui/vant#10897]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

vant官方文档中，按需引入组件（推荐）一项，第二步已经配置了插件（unplugin-vue-components），为什么第三步还有引入组件后使用，理论上不应该有第三步了吧？

### 重现步骤

无

### 设备/浏览器

无

**Comment by chenjiahan** [comment]
引入组件确实不是必须的。

文档里主要用到了 unplugin-vue-components 的按需引入样式能力，所以把引用组件的步骤也写上去了，后续我们优化下文档
