### ISSUE TITLE
在一个页面中同时使用toast和popup组件，toast的灰色背景样式会被popup覆盖为白色

### ISSUE THREAD

**Issue by zhishanYin** [vant-ui/vant#10906]
### 重现链接

https://gitee.com/webh5/toast-and-popup-issues

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

在同一个页面中，引入 toast和popup，toast的背景就会变成白色，就会看不见toast

### 重现步骤

![image](https://user-images.githubusercontent.com/20438123/184303839-67e5769f-5e2d-4c92-b1a4-71c186b773ef.png)
![image](https://user-images.githubusercontent.com/20438123/184303959-23a15bb2-f24c-4ef7-80e3-45b16b743c57.png)
![image](https://user-images.githubusercontent.com/20438123/184304102-c5e47788-4ca7-488f-add0-d95f88c04e8a.png)
![image](https://user-images.githubusercontent.com/20438123/184304244-dad09300-232b-4b8b-b27f-7041414b5844.png)

**Comment by chenjiahan** [comment]
链接无法访问

![image](https://user-images.githubusercontent.com/7237365/184461516-f7397909-d477-49cb-b2f1-92acb05621d7.png)

**Comment by zhishanYin** [comment]
![image](https://user-images.githubusercontent.com/20438123/184812519-24395e95-00aa-4d11-bc3f-56058feb19b4.png)
已开源可以访问了

**Comment by zhishanYin** [comment]
https://gitee.com/webh5/toast-and-popup-issues

**Comment by KeJunMao** [comment]
+1

**Comment by Nelk98** [comment]
雀食。

**Comment by wjw-gavin** [comment]
全局引入css确实会发生这种情况，如果按需引入，可以避免这种情况。

**Comment by chenjiahan** [comment]
> https://gitee.com/webh5/toast-and-popup-issues

这个项目的样式引入方式有问题，同时使用了「全量引入样式」和「按需引入样式」两种方式，导致最终的组件样式是双份的，产生了覆盖现象。

解决方法是把「全量引入样式」移除掉，保留「按需引入样式」即可。

**Comment by Mashirowww** [comment]
> [试试这个](https://vant-ui.github.io/vant/#/zh-CN/quickstart#4.-yin-ru-han-shu-zu-jian-de-yang-shi)

很好地解决了问题 赞
