### ISSUE TITLE
[Feature Request] add demo of vue3-ts to vant-demo

### ISSUE THREAD

**Issue by wjw-gavin** [vant-ui/vant#10903]
### 这个功能解决了什么问题？

add demo of vue3-ts (script-setup)

### 你期望的 API 是什么样子的？

Hi, I really like vant-ui very much and I added `vue3-ts` demo to `vant-demo`, it's relatively simple so I just passed my own test, can you check it and merge it?  (if there are no bugs) Thanks!

[Here](https://github.com/vant-ui/vant-demo/pull/102)

**Comment by chenjiahan** [comment]
Thanks for your contribution! The pull request has been merged.
