### ISSUE TITLE
Vant datetime picker is not work in IOS

### ISSUE THREAD

**Issue by BuuTii262** [vant-ui/vant#10907]
### 重现链接

https://vant-ui.github.io/vant/#/en-US/datetime-picker

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

Date time picker is not show in IOS but show in adroid, Window, and Linux.
How can I solved it 

### 重现步骤

Date time picker is not display in IOS

### 设备/浏览器

iOS all browser

**Comment by chenjiahan** [comment]
If you encounter the problem that the component cannot be rendered on the iOS, please make sure that the new Date ('2020-01-01') is not used when creating the Date object, iOS does not support the date format separated by dashes, the correct way is new Date ('2020/01/01').

Detailed explanation: [stackoverflow](https://stackoverflow.com/questions/13363673/javascript-date-is-invalid-on-ios).
