### ISSUE TITLE
[Bug Report] 在v2.12.28上， click-tab要比before-change先执行，没法在点击生效前做作拦截

### ISSUE THREAD

**Issue by 973257307** [vant-ui/vant#10900]
### 重现链接

--

### Vant 版本

2.12.28

### 描述一下你遇到的问题。

在Vant2.x里面， click-tab要比before-change先执行，没法在点击生效前做作拦截

### 重现步骤

1、快速点击tab，第一个tab的数据还没回来，我就就切换到下个tab。预期是要要等第一个tab的结果返回了。我才能成功的切换的其他的tab,不然会就造成tab和下面的列表数据不对应。之前在vant3也遇到了，提交了bug。在vant3解决。但是vant2.x的还有这个问题，现在是我vue2 用vant2。没法直接用vant3。

**Comment by chenjiahan** [comment]
可以提 PR 哈，参见：

![image](https://user-images.githubusercontent.com/7237365/184116865-3fef7b21-185a-467e-aa0c-813441b67def.png)

**Comment by 973257307** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 晚上6:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vant-ui/vant] [Bug Report] 在v2.12.28上， click-tab要比before-change先执行，没法在点击生效前做作拦截 (Issue #10900)





 
可以提 PR 哈，参见：
