### ISSUE TITLE
Toast在Vue3中无法正常使用

### ISSUE THREAD

**Issue by qifeiweb** [vant-ui/vant#10901]
### 重现链接

https://vant-ui.github.io/vant-demo/#/goods

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

在vue3.2 setup中，如何使用Toast？官方的事例怎么样都无法弹出提示，而且官方的demo[vant-ui.github.io/vant-demo](https://vant-ui.github.io/vant-demo)中Vue3的Toast也无法正常提示

### 重现步骤

请使用官方demo，进入vue3文件夹，npm install
1，点击立即购买
2，无法弹出提示‘暂无后续逻辑~’

### 设备/浏览器

Google Chrome

**Comment by wjw-gavin** [comment]
这里需要引入 
```js
import 'vant/es/toast/style';
```
[这里有说明的](https://vant-ui.github.io/vant/#/zh-CN/quickstart#4.-yin-ru-han-shu-zu-jian-de-yang-shi)
![image](https://user-images.githubusercontent.com/19986739/184116601-a659bdd5-aac5-4b89-b3af-516ade155e2f.png)

**Comment by SilentFlute** [comment]
可以可以, 我说怎么我使用插件, 按需引入了, 然后样式还不对, 还以为是这个问题: #10906 , 但看了之后发现 全量, 按需只能二选一, 我如果`import 'vant/lib/index.css';` 那么`Toast`样式正常了, 但自己写的其他样式会被覆盖, 删掉则`Toast`又没有样式, 然后看到这个`issue`, 原来文档一开始就提到了, 害, 一开始没用到`Toast`, 然后就略过这一部分了, 想着用到`Toast`了, 那就去`Toast`的文档里面看 >_<
