### ISSUE TITLE
search组件通过ConfigProvider无法修改--van-search-input-height 高度

### ISSUE THREAD

**Issue by freedomwebcn** [vant-ui/vant#10905]
### 重现链接

https://codesandbox.io/s/elegant-bogdan-c52n5l?file=/src/App.vue

### Vant 版本

3.5.4

### 描述一下你遇到的问题。

我想要修改search组件的高度，通过ConfigProvider 组件包裹后修改，传入配置项无法修改成功。

### 重现步骤

见重现链接

**Comment by chenjiahan** [comment]
确实有问题，下个版本会修复
