### ISSUE TITLE
[Bug Report] vant2的van-empty组件中图片不显示的问题

### ISSUE THREAD

**Issue by Ay1c** [vant-ui/vant#10917]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/empty

### Vant 版本

2.12.31

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/30484013/184571025-84c9638c-da05-43c0-82da-5c5aaf370553.png)

### 重现步骤

打开后空的图片不显示

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/184612614-bcba5282-13be-4bdf-aa46-8f1c5b27c057.png)
