### ISSUE TITLE
[Bug Report] 在popup组件中嵌套DropdownMenu组件，下拉选项定位错误

### ISSUE THREAD

**Issue by esilyzhang** [vant-ui/vant#10914]
### 重现链接

https://codesandbox.io/s/vant-3-issue-template-forked-z3nzc8?file=/src/App.vue

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

```html
 <van-popup v-model:show="show">
      <div class="container">
        <van-dropdown-menu>
          <van-dropdown-item v-model="value1" :options="option1" />
        </van-dropdown-menu>
      </div>
    </van-popup>
```
van-popup 中使用 van-dropdown-menu 出现的下拉框位置计算错误。

分析之后，出现问题的原因是：

van-popup 使用了`transform: translate3d(-50%, -50%, 0)`进行居中，van-dropdown-item 是使用`fixed`进行定位的，这时van-dropdown-item的定位容器将会变更为 van-popup，而不是 viewport，所有出现定位错误。

### 重现步骤

```html
 <van-popup v-model:show="show">
      <div class="container">
        <van-dropdown-menu>
          <van-dropdown-item v-model="value1" :options="option1" />
        </van-dropdown-menu>
      </div>
    </van-popup>
```

### 设备/浏览器

Chrome（最新），Edge（最新）

**Comment by Alanscut** [comment]
Duplicated of #10661
