### ISSUE TITLE
van-empty样式错乱

### ISSUE THREAD

**Issue by 18674801565** [vant-ui/vant#10918]
### 重现链接

https://codesandbox.io/s/cold-forest-gcw5z3?file=/src/App.vue

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

<img width="1704" alt="image" src="https://user-images.githubusercontent.com/43339400/184617536-c053beb8-ea1d-4501-a29f-5060f38c1e27.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/43339400/184617612-047cb3e0-941d-4109-9c56-92761a578c9a.png">

### 重现步骤

与tabs标签一起使用

**Comment by chenjiaj** [comment]
我也遇到相同的问题了

**Comment by chenjiaj** [comment]
找到问题了，svg里边的id是固定的，一个页面上不能出现多个van-empty，否则id会重复

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复
