### ISSUE TITLE
在组件mounted内 获取 offsetHeight, offsetWidth 等类似属性, 影响switch初始加载效果

### ISSUE THREAD

**Issue by chest233** [vant-ui/vant#10916]
### 重现链接

https://codesandbox.io/s/throbbing-worker-oxghnl?file=/src/App.vue

### Vant 版本

2.12.48

### 描述一下你遇到的问题。
switch组件, 初始设置为close
在mounted中, 修改状态为open
若果在这个mounted中尝试读取dom元素offsetHeight, offsetWidth类似属性时, 页面中switch按钮会有一个从关闭到打开的过渡效果
奇怪的是, 去掉读取offsetHeight语句, 过渡效果不再出现

### 重现步骤

1. 在mounted中获取dom元素offsetHeight属性, switch 初始渲染会有一个从关闭到打开的动画
2. 去掉读取offsetHeight语句, 刷新页面, switch初始渲染过渡效果不再出现

### 设备/浏览器

chrome(104.0.5112.79); firefox(102.0.1);  微信浏览器(微信版本8.0.26, ios版本15.6)

**Comment by Alanscut** [comment]
![image](https://user-images.githubusercontent.com/21104054/184612725-5b23e9c5-bc0f-457e-86e0-c3ac7b6090ea.png)
