### ISSUE TITLE
在vue3+vite单独引入不了vant自身的css 导致ImagePreview.. 等部分样式无显示;

### ISSUE THREAD

**Issue by cl-cc** [vant-ui/vant#10924]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/image-preview

### Vant 版本

3.4.3

### 描述一下你遇到的问题。

vue": "^3.2.37",
"vite": "^3.0.7",
<img width="714" alt="image" src="https://user-images.githubusercontent.com/57168312/185030375-9349fd88-3904-4fd2-a89c-eb80df4502cd.png">

### 重现步骤

点击后 无法渲染样式 报错

### 设备/浏览器

移动端

**Comment by cl-cc** [comment]
直接在main.ts中引入 全部样式 是ok的 import 'vant/lib/index.css';

**Comment by chenjiahan** [comment]
试了下没问题，可以升级最新版试下
