### ISSUE TITLE
[Bug Report] PullRefresh等组件会在控制台报非被动事件警告

### ISSUE THREAD

**Issue by ifugly** [vant-ui/vant#10920]
### 重现链接

https://vant-contrib.gitee.io/vant/v4/#/zh-CN/pull-refresh

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

使用PullRefresh等需要监听滚动事件时控制台报错：
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.
vant官网也有此警告

### 重现步骤

1.访问vant官网找到PullRefresh组件页面
2.打开F12调试即可重现

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
PullRefresh 已修复，其他组件后续也会陆续修复
