### ISSUE TITLE
Toast组件调用导致列表滚动条置顶

### ISSUE THREAD

**Issue by 18674801565** [vant-ui/vant#10922]
### 重现链接

https://codesandbox.io/s/thirsty-bose-v823s6?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

### Vant 版本

3.5.3

### 描述一下你遇到的问题。

<img width="309" alt="image" src="https://img2020.cnblogs.com/blog/2102264/202107/2102264-20210730170932262-2031778755.gif">

### 重现步骤

1.显示toast
2.点击加载，list添加数据

### 设备/浏览器

微信webview

**Comment by chenjiahan** [comment]
复现链接无效，麻烦提供可复现该问题的 codesandbox 链接。
