### ISSUE TITLE
[Feature Request] 如果基于vant进行组件二次开发，如何引入vant CSS

### ISSUE THREAD

**Issue by Gintangible** [vant-ui/vant#10934]
### 这个功能解决了什么问题？

基于vant组件进行组件二次开发，能够延用vant样式

### 你期望的 API 是什么样子的？

基于vant组件进行组件二次开发，能够使用vant样式

**Comment by chenjiahan** [comment]
直接 import 引用就行

**Comment by Gintangible** [comment]
> 直接 import 引用就行

基于vant-cli开发的话，在什么地方进行引入呢？在vant.config.mjs直接引入的话，直接打包会报错

如果通过以下方式，样式会正常，
```
build: {
    css: {
      base: '../node_modules/vant/lib/index.css',
      preprocessor: 'less',
    },
  },
```
但是打包的话，结果跟路径强绑定了 `@import"E:/glib/vue-components/node_modules/vant/lib/index.css";`

**Comment by chenjiahan** [comment]
为啥不在代码里引入呢

**Comment by Gintangible** [comment]
@chenjiahan 因为在vant组件基础上开发的，基本每个组件+demo都会用的vant组件，用按需加载的引用方式的话，需要引用很多次，所以想全局引用的。

**Comment by chenjiahan** [comment]
你可以把 css.base 指向 src 下的某个基础样式文件，然后在这个样式文件里引用 vant 的 CSS 文件

**Comment by Gintangible** [comment]
@chenjiahan  现在我这边是这边做的，将vant样式复制过来用的，但这样的话，当vant样式做了调整，或者新增组件样式的时候，我还需要关注base的样式是否需要做出变化。所以vant-cli可否考虑支持全局引入样式。

ps: 试了在基础样式文件用 `@import url('vant/lib/index.css');` 引入，这样不行。

**Comment by chenjiahan** [comment]
> vant-cli可否考虑支持全局引入样式。

base.css 就是这个作用的，只是不适用于 node_modules 中的样式文件。

> 试了在基础样式文件用 @import url('vant/lib/index.css'); 引入，这样不行。

直接 import 呢？不使用 @import url(

**Comment by Gintangible** [comment]
@chenjiahan 直接import 的话，yarn build 编译过不了

**Comment by zhanglong1009** [comment]
我现在也遇到了同样的问题，目前用的vant-cli7.0，想全局引入vant的样式，试了新建一个css文件，使用@import，然后在base里设置路径，但是不起作用
