### ISSUE TITLE
van-radio 设置checked-color无效

### ISSUE THREAD

**Issue by CaoJ20132014** [vant-ui/vant#10932]
### 重现链接

van-radio 设置checked-color无效

### Vant 版本

2.12.9

### 描述一下你遇到的问题。

van-radio 设置checked-color无效

### 重现步骤

van-radio 设置checked-color无效

**Comment by wjw-gavin** [comment]
最好提供下你的代码....
我这试的是可以的

[https://codesandbox.io/s/vant-3-issue-template-forked-qsd3nz?file=/src/App.vue](https://codesandbox.io/s/vant-3-issue-template-forked-qsd3nz?file=/src/App.vue)

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接，无效的 issue 将被关闭，感谢配合
