### ISSUE TITLE
van-search 里input字体颜色无法更改

### ISSUE THREAD

**Issue by manyhelp** [vant-ui/vant#10931]
### 重现链接

无

### Vant 版本

3.5.4

### 描述一下你遇到的问题。

van-search 背景改黑色后。里面输入的字无法改颜色，自定义样式也没用

### 重现步骤

input字体颜色无法更改

**Comment by wjw-gavin** [comment]
最好能提供代码，看下你是怎么写的....

**Comment by chenjiahan** [comment]
请提供 codesandbox 复现链接，无效的 issue 将被关闭，感谢配合
