### ISSUE TITLE
[Bug Report] 4.0.0-beta.0 API调整后使用函数报错

### ISSUE THREAD

**Issue by wltj920** [vant-ui/vant#10940]
### 重现链接

没有链接

### Vant 版本

4.0.0-beta.0

### 描述一下你遇到的问题。

可能是V4的文档没有更新，使用新版函数例如

* showToast
* showDialog
* showNotify

的时候，无论怎么配置，都会报类以错：

```
These dependencies were not found:

* vant/es/show-dialog in ./src/utils/request.js
* vant/es/show-dialog/style in ./src/utils/request.js

To install them, you can run: npm install --save vant/es/show-dialog vant/es/show-dialog/style
```

### 重现步骤

1. 在原有的`4.0.0-alpha.2`版本中修改`package.json`中的vant版本为`4.0.0-beta.0`
2. 在项目中某js文件中写
``` javascript
import {showDialog} from "vant";

showDialog({message: 'Hello'}).then(() => {
    console.log('123');
});
```
3. 运行项目报错

### 设备/浏览器

Webstorm

**Comment by chenjiahan** [comment]
这是 babel-plugin-import 导致的，从 4.0.0-beta.0 版本开始不再需要 babel-plugin-import 了，请参考 https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3#yi-chu-babel-plugin-import 进行移除

**Comment by wltj920** [comment]
> 这是 babel-plugin-import 导致的，从 4.0.0-beta.0 版本开始不再需要 babel-plugin-import 了，请参考 https://vant-ui.github.io/vant/v4/#/zh-CN/migrate-from-v3#yi-chu-babel-plugin-import 进行移除

的确是，但我是删除了`.babelrc`文件后才搞定的

**Comment by chenjiahan** [comment]
> 删除了.babelrc文件后才搞定的

不用删整个文件，删单个插件就行。

如果删除插件没生效，可能是编译有缓存了。
