### ISSUE TITLE
[Bug Report] vant3.6.0，tabbar组件bug

### ISSUE THREAD

**Issue by gaoqiya** [vant-ui/vant#10953]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/tabbar

### Vant 版本

3.6.0

### 描述一下你遇到的问题。

使用vant3.6.0，tabbar组件编译后无法定位到页面的底部。排查后发现，页面上会被其他样式覆盖，但我没有用到那个样式，如图：
![image](https://user-images.githubusercontent.com/45963590/185792420-f138a943-218b-45b0-811a-51e492955313.png)
![image](https://user-images.githubusercontent.com/45963590/185793385-1bb780d4-0e7d-41b2-b6bf-47843cd28a1b.png)
我是使用的按需引入组件。

### 设备/浏览器

所有设备

**Comment by chenjiahan** [comment]
麻烦提供一个复现问题的 codesandbox 链接或仓库地址

**Comment by gaoqiya** [comment]
> 麻烦提供一个复现问题的codeandbox链接或仓库地址

仓库地址：https://github.com/gaoqiya/test
本地打包后可以复现，麻烦给看看，谢谢！

**Comment by chenjiahan** [comment]
看了下是 vite 的 bug，导致 CSS 顺序错误了，可以到相关 issue 中跟进：

- https://github.com/vitejs/vite/issues/3924
- https://github.com/vitejs/vite/pull/9278

**Comment by chenjiahan** [comment]
如果想避免这个问题，可以先在入口文件中全量引入样式，然后把 unplugin-vue-components 的自动样式引入给关掉
