### ISSUE TITLE
[Bug Report]关于progress组件没有精准计算出宽度，导致里面的portion计算超出了外面的宽度溢出了

### ISSUE THREAD

**Issue by forestxieCode** [vant-ui/vant#10959]
### 重现链接

https://codesandbox.io/s/clever-margulis-cr4j3q?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

2.11.0

### 描述一下你遇到的问题。

![现象](https://user-images.githubusercontent.com/43224707/186173112-38cada3d-3279-4804-bddc-85f012fce96b.png)
progress组件没有精准计算出宽度，导致里面的portion计算超出了外面的宽度溢出了

### 重现步骤

重现步骤:

1. 排列在一行的三个元素，设置非progress组件延时显示
2. 设置progress的组件为改行的剩余宽度
3. percentage的占比为100% 

### 设备/浏览器

谷歌手机模拟器

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/187014739-3c980242-bcad-4b66-baac-646599c4f37d.png)

需要调一下 resize 方法
