### ISSUE TITLE
关于vant2垂直滑块方向是反的，0在顶部，100在底部问题。建议进行调整

### ISSUE THREAD

**Issue by xiongchangming** [vant-ui/vant#10958]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/slider

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

vant2垂直滑块方向是反的，0在顶部，100在底部问题。在垂直滑块使用时很不方便。希望能根据实际使用情况进行调整

### 重现步骤

vant垂直滑块方向是反的，0应该在底部，100应该在顶部才对。或者有没有可以进行倒置处理方法。

**Comment by chenjiahan** [comment]
v3 支持 reverse 属性，v2 不支持哈。

在 v2 里，你可以格式化一下 value，比如使用 `100 - value` 作为最终的值。
