### ISSUE TITLE
[Bug Report] Dialog.confirm调用弹框样式不完整

### ISSUE THREAD

**Issue by isaacduane** [vant-ui/vant#10962]
### 重现链接

https://m-test.gjhyss.com/detail/101

### Vant 版本

3.5.4

### 描述一下你遇到的问题。

调用Dialod.confirm方法弹框，样式显示有丢失。
```
Dialog.confirm({
    className: 'confirm-exchange',
    title: '标题',
    width: '90%',
    closeOnClickOverlay: true,
    messageAlign: 'left',
})
```
![image](https://user-images.githubusercontent.com/1934959/186349114-7c6d11f3-7f66-44e9-a565-277d5bcead61.png)

在template中放置了vant-dialog元素（并不做任何show操作）后再次调用Dialog.confirm方法样式才显示完全。
```
<van-dialog v-if="false" :show="false" title="标题" show-cancel-button>
    <img src="https://fastly.jsdelivr.net/npm/@vant/assets/apple-3.jpeg" />
</van-dialog>
```

![image](https://user-images.githubusercontent.com/1934959/186349492-69b566b6-1c16-4039-afd5-fce722cce2d6.png)

下方图自定义样式：
```
.confirm-exchange {
  .van-dialog__header {
    font-size: 20px;
    font-weight: 700;
    color: rgba(0, 0, 0, 0.9);
    margin-bottom: 5px;
    background: linear-gradient(180deg, #f2cdff, #ffffff);
  }
  .van-dialog__footer {
    flex-direction: column-reverse;
    padding: 0 20px 30px 20px;
    .van-button {
      &:before,
      &:after {
        display: none;
      }
    }
    .van-dialog__confirm {
      background-color: #6e00cc;
      border-radius: 24px;
      height: 44px;
      line-height: 44px;
      color: #fff;
    }
    .van-dialog__cancel {
      height: 44px;
      line-height: 44px;
    }
  }
}
```

### 重现步骤

1. 点击按钮click调用Dialog.confirm
2. 弹框样式有丢失
3. 在template中放置一段vant-dialog元素
4. 再次调用样式显示完全

**Comment by chenjiahan** [comment]
可以看下文档里的这部分内容：

![image](https://user-images.githubusercontent.com/7237365/186427595-25ba69ec-795c-4a8c-a288-3921d4218e11.png)

https://vant-ui.github.io/vant/#/zh-CN/quickstart
