### ISSUE TITLE
[Feature Request] tab开启swipeable属性后，调用resize不会刷新tab的content

### ISSUE THREAD

**Issue by yushaoyi** [vant-ui/vant#10960]
### What problem does this feature solve?

tab开启了swipeable，包含tab的容器的宽度从80%变为100%后，手动调用tab的resize方法，发现tab的宽度并不会发生变化即自适应，看源码似乎是不会刷新内部的swiper，没有同步调用swiper的resize方法

### What does the proposed API look like?

<van-tabs
              ref="tabs"
              v-model:active="activeTab"
              swipeable
            >

**Comment by chenjiahan** [comment]
下个版本会修复此问题
