### ISSUE TITLE
field中使用label插槽时，label中的数据双向绑定问题

### ISSUE THREAD

**Issue by luckyisLhh** [vant-ui/vant#10968]
### 重现链接

无

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

field中使用label插槽时，label中的数据双向绑定问题，但是数据绑定数据清空时，label中一直保留一个字符

### 重现步骤

1. 绑定插槽
![image](https://user-images.githubusercontent.com/56502832/186659641-f972281b-cc34-4815-baba-ca8ce86e1eb2.png)
2. 数据双向绑定
![image](https://user-images.githubusercontent.com/56502832/186660014-9d630370-e847-47ee-9578-e2576b25ba0a.png)
3. 但是输入框中无数据时，label数据还是会保留一位
![image](https://user-images.githubusercontent.com/56502832/186660732-e2fd0ecc-d6b4-4776-ae2d-af93c21721ff.png)

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 复现链接
