### ISSUE TITLE
[Feature Request] van-tabs在开启swipeable后第一个标签页面拦截向右滑动手势

### ISSUE THREAD

**Issue by pcccccc** [vant-ui/vant#10963]
### 这个功能解决了什么问题？

您好，我是一名App开发者，目前使用Vant遇到了下面的问题：

Tab标签页开启swipeable后，在卡片之间切换并没有问题，但是在第一个tab上手指向右滑动时，tab会占用此手势。

希望可以在第一个tab时可以正确相应手指向右swipe的动作。

如图所示：

![tutieshi_640x1383_6s](https://user-images.githubusercontent.com/13974510/186408397-ca37ed94-7229-4bee-93d5-3b91dfa85742.gif)

使用版本：4.0.0-beta.0

### 你期望的 API 是什么样子的？

暂无

**Comment by chenjiahan** [comment]
了解，后续会看下能否处理这种场景

**Comment by yushaoyi** [comment]
我用的3.5版本，开启了swipeable后，给第一个tab加了个指令，里面可以实现正常的事件监听，实现自定义的向右滑动的事件。
不知道@pcccccc 是不是想要这种效果

**Comment by pcccccc** [comment]
> 我用的3.5版本，开启了swipeable后，给第一个tab加了个指令，里面可以实现正常的事件监听，实现自定义的向右滑动的事件。 不知道@pcccccc 是不是想要这种效果

应该是类似的，我这边希望在第一个tab内向右滑动可以由tab的父view去相应这个事件，而目前是被tab占用了。我这边算是一个前端小白。。google了几个方法都没有实现这个功能。。如果您这边实现了的话可以上传到您的仓库让我学习学习吗？

**Comment by pcccccc** [comment]
@chenjiahan 您好请问这个新的需求什么时候会合并到4.0.0版本呢

**Comment by chenjiahan** [comment]
已经合并了，还没发版，预计本周末发版

**Comment by pcccccc** [comment]
> 已经合并了，还没发版，预计本周末发版

好的，非常感谢

**Comment by pcccccc** [comment]
> 已经合并了，还没发版，预计本周末发版

老兄刚看了一下你在3.6.2版本中修复了这个问题但是4.0.0 rc1并没有修复....

**Comment by chenjiahan** [comment]
有的呀，4.0.0-rc.0 包含了 v3 最新改动的

**Comment by pcccccc** [comment]
> 有的呀，4.0.0-rc.0 包含了 v3 最新改动的

确实有，我的问题
