### ISSUE TITLE
PullRefresh 加载过程中的提示文案无法修改，加载过程的插槽也无法使用

### ISSUE THREAD

**Issue by dxr11111** [vant-ui/vant#10969]
### 重现链接

https://vant-contrib.gitee.io/vant/v2/#/zh-CN/pull-refresh

### Vant 版本

2.12.48

### 描述一下你遇到的问题。

PullRefresh下拉刷新时 加载过程中的提示文案无法修改，加载过程的插槽也无法使用

### 重现步骤

 <template #loading>
        <img class="doge" src="https://img01.yzcdn.cn/vant/doge-fire.jpg" />
      </template>

### 设备/浏览器

google Chrome

**Comment by chenjiahan** [comment]
请提供有效的 codesandbox 重现链接
