### ISSUE TITLE
[Bug Report] 4.0.0-beta.0版本无法使用Space组件

### ISSUE THREAD

**Issue by Nakus0426** [vant-ui/vant#10972]
### 重现链接

https://codesandbox.io/s/space-component-missed-s5kvvq?file=/src/App.vue

### Vant 版本

4.0.0-beta.0

### 描述一下你遇到的问题。

在4.0.0-beta.0版本中无法使用Space组件，查看node_modul/vant/es文件夹下未找到space相关的文件
注：项目使用pnpm安装vant

### 重现步骤

1. 使用pnpm安装4.0.0-beta.0版本的vant
2. 使用Space组件

### 设备/浏览器

Microsoft Edge 版本 104.0.1293.63 (正式版本) (64 位)

**Comment by chenjiahan** [comment]
麻烦看下更新日志，4.0.0-beta.1 才支持
https://vant-ui.github.io/vant/v4/#/zh-CN/changelog

**Comment by Nakus0426** [comment]
> 麻烦看下更新日志，4.0.0-beta.1 才支持 https://vant-ui.github.io/vant/v4/#/zh-CN/changelog

我看的是gitee下的[文档](https://vant-contrib.gitee.io/vant/v4/#/zh-CN/changelog)，这文档还没更新到beta1....

**Comment by chenjiahan** [comment]
gitee 同步有延迟。。
