### ISSUE TITLE
[Feature Request] 支持parcel的按需加载

### ISSUE THREAD

**Issue by gxy5202** [vant-ui/vant#10992]
### 这个功能解决了什么问题？

目前按需加载插件仅支持vite/webpack/rollup/vue-cli，parcel目前的打包效率也挺高，是否能增加parcel的插件？

### 你期望的 API 是什么样子的？

支持parcel的按需加载

**Comment by chenjiahan** [comment]
按需加载插件并不是 Vant 团队维护的，建议你到插件的 GitHub 仓库下反馈哈

https://github.com/antfu/unplugin-vue-components

**Comment by gxy5202** [comment]
> 按需加载插件并不是 Vant 团队维护的，建议你到插件的 GitHub 仓库下反馈哈
> 
> https://github.com/antfu/unplugin-vue-components

好的
