### ISSUE TITLE
[Bug Report] Dialog组件问题

### ISSUE THREAD

**Issue by wuanrin** [vant-ui/vant#10998]
### 重现链接

https://codesandbox.io/s/fast-shape-wy77s9?file=/src/components/DialogDemo.vue

### Vant 版本

3.6.1

### 描述一下你遇到的问题。

1. Slot内容没有显示
```vue
<Dialog v-model:show="dialogVisible" title="弹窗"> 我是一个弹窗 </Dialog>
```
实际显示：
![image](https://user-images.githubusercontent.com/8286811/187824651-94875a70-0259-4fe3-a8b9-76c76bd8beca.png)

2. `v-model:show`属性设置的是`false`，弹窗却显示了
3. 设置`v-model:show`为`true`时报错
![image](https://user-images.githubusercontent.com/8286811/187825123-e076b766-705a-4161-a8ee-3dadd3a38710.png)

### 重现步骤

1. 刷新页面
2. 点击按钮设置v-model:show为true

### 设备/浏览器

Chrome

**Comment by wjw-gavin** [comment]
![image](https://user-images.githubusercontent.com/19986739/187839990-b6854fff-d3ef-43ad-b589-b7c0c0914fe3.png)

**Comment by wjw-gavin** [comment]
解答在这里：
https://github.com/vant-ui/vant/issues/10858#issuecomment-1200395766

**Comment by wuanrin** [comment]
> 解答在这里： [#10858 (comment)](https://github.com/vant-ui/vant/issues/10858#issuecomment-1200395766)

感谢，问题解决
