### ISSUE TITLE
vant4正式版本什么时候发版

### ISSUE THREAD

**Issue by 18300618319** [vant-ui/vant#10993]
### 这个功能解决了什么问题？

vant4正式版本什么时候发版

### 你期望的 API 是什么样子的？

vant4正式版本什么时候发版

**Comment by chenjiahan** [comment]
预计 9 ~ 10 月会发布 4.0.0-rc 版本，11 ~ 12 月发布 4.0.0 正式版本。

**Comment by FE-runner** [comment]
> 预计 9 ~ 10 月会发布 4.0.0-rc 版本，11 ~ 12 月发布 4.0.0 正式版本。

想用4 但是怕稳定性问题 所以按住了

**Comment by chenjiahan** [comment]
等 rc 阶段应该会比较稳定了哈
