### ISSUE TITLE
[Bug Report] Notify组件的背景色被Popup背景色覆盖

### ISSUE THREAD

**Issue by wltj920** [vant-ui/vant#10991]
### 重现链接

无

### Vant 版本

4.0.0-beta.1

### 描述一下你遇到的问题。

使用showNotify方法例如以下代码：

```typescript
showNotify({type: 'success', message: '操作成功'});
```

可以发现Notify的背景色变成了Popup的背景色
![image](https://user-images.githubusercontent.com/10513736/187218157-7c9f03b0-67dc-436c-a4cb-012296c225dd.png)

### 重现步骤

如上图

### 设备/浏览器

Microsoft Edge

**Comment by wjw-gavin** [comment]
看下是否和这个是同样的问题？ https://github.com/vant-ui/vant/issues/10906

**Comment by wltj920** [comment]
> 看下和这个是否是同样的问题？ #10906

不太一样，我并没有引用Popup这个组件

**Comment by wjw-gavin** [comment]
我刚刚试了下，最初确实是你说的这种情况，找到原因如下：
这里需要引入 
```js
import 'vant/es/notify/style';
```
[这里有说明的](https://vant-contrib.gitee.io/vant/v4/#/zh-CN/quickstart#4.-yin-ru-han-shu-zu-jian-de-yang-shi)

![image](https://user-images.githubusercontent.com/19986739/187335284-64189ea4-7573-4d88-9edd-0fd8365fb9f8.png)

**Comment by wjw-gavin** [comment]
另外，我发现很多人在使用类似 toast 函数组件时，都是直接使用，并没有看到需要单独引入样式的注意项，因此我们是否可以把这些注意项放到各个相关组件中呢？这样在使用时即可看到  @chenjiahan

**Comment by chenjiahan** [comment]
> 另外，我发现很多人在使用类似 toast 函数组件时，都是直接使用，并没有看到需要单独引入样式的注意项，因此我们是否可以把这些注意项放到各个相关组件中呢？这样在使用时即可看到 @chenjiahan

可以的哈，我加一下

**Comment by EthanVn** [comment]
// 解决Vant样式冲突, Notify被Popup覆盖
.van-notify--primary {
  background-color: var(--van-notify-primary-background) !important;
}
.van-notify--success {
  background-color: var(--van-notify-success-background) !important;
}
.van-notify--danger {
  background-color: var(--van-notify-danger-background) !important;
}
.van-notify--warning {
  background-color: var(--van-notify-warning-background) !important;
}
