### ISSUE TITLE
下拉刷新和加载做的完全错误的你们是怎么在使用

### ISSUE THREAD

**Issue by shijunti19** [vant-ui/vant#10990]
### 重现链接

https://codesandbox.io/embed/vant-3-issue-template-forked-054gw4?fontsize=14&hidenavigation=1&theme=dark

### Vant 版本

4.0.0

### 描述一下你遇到的问题。

组件的下拉刷新和加载完全没有按照实际场景设计，根本无法使用的，下拉还没滚动到顶部就已经触发刷新了！
滚动加载完全无法使用
PC上mobile模式完全不兼容

### 重现步骤

你们按照正常场景制作，获取数据，加载好，然后下拉刷新，滚动加载！
你们的demo太简单，没有测试到存在的问题，根本无法使用！
![1](https://user-images.githubusercontent.com/5392211/187211251-329e9627-70f9-4fbf-b595-90eaeecf905b.gif)
你看我下拉加载后，网上滚动还没滚动到顶部他就已经触发刷新！

**Comment by chenjiahan** [comment]
codesandbox 链接无法复现你说的问题。

当你判断组件是完全错误的之前，建议先反思下是不是自己的用法有问题。

**Comment by shijunti19** [comment]
@chenjiahan 是你们的demo太简单了啊，你们的demo大部分没按照实际场景做，都是单个测试单个完成。这个刷新要滚动到顶部，无法再滚动才可以触发，你们是往下拉下，滚动条往上滚动下就触发了，根本不需要什么demo啊

**Comment by shijunti19** [comment]
@chenjiahan 问题的重点在于，你们开发的组件不放到实际场景中测试，都是单个测试看下功能可以就好了，但是实际场景因为一些小问题根本无法使用，例如按钮没有按钮组的，多个排布很那看其他组件都有button-group
ConfigProvider 组件没有把语言切换整合进去
Image 没有点击预览功能
Layout 布局不支持按照屏幕大小分配sl=,xl=xxl=这种
Field 输入框没有垂直模式！
哎，你们几乎没有一个组件是正常开发的，都是一堆缺陷

**Comment by chenjiahan** [comment]
> ConfigProvider 组件没有把语言切换整合进去

语言切换有单独的 Locale 组件，为什么一定要整合到 ConfigProvider 里呢？

> Image 没有点击预览功能

建议你看下 ImagePreview 组件。

> Layout 布局不支持按照屏幕大小分配

移动端通常是基于 flex 和栅格布局，我不觉得 sl/xl 这种方式是必须的

> 按钮没有按钮组

把按钮放在一起也不是什么难事，没必要什么都指望组件库来提供，Ant Design 也不再提供 Button Group 了

![image](https://user-images.githubusercontent.com/7237365/187577881-c0432113-6c24-4d8b-ba0a-94102985611d.png)

> Field 输入框没有垂直模式

同上。

**Comment by chenjiahan** [comment]
> 这个刷新要滚动到顶部，无法再滚动才可以触发，你们是往下拉下，滚动条往上滚动下就触发了，根本不需要什么demo啊

建议你看下这个 demo 里的下拉刷新示例再下结论。

https://vant-ui.github.io/vant/#/zh-CN/list

**Comment by shijunti19** [comment]
@chenjiahan 
https://github.com/vant-ui/vant/issues/3823
找到了
html,
body {
  width: 100%;
  height: 100%;
  overflow: visible;
   overflow-x: hidden;
}
vben-admin他带有   overflow-x: hidden;
然后你们没注明解决办法，一直找不到原因
我现在只能直接注释   overflow-x: hidden;
不过我觉得
    const scrollParent = useScrollParent(root);
      reachTop = getScrollTop(scrollParent.value) === 0;
useScrollParent无法兼容上述第四种情况下，应该让我们用户自己传入，是使用windows滚动还是body吧！

**Comment by nusheactx** [comment]
哈哈。我想笑。
