### ISSUE TITLE
JSX 元素类型“VanSwitch”不具有任何构造签名或调用签名

### ISSUE THREAD

**Issue by qzy1** [vant-ui/vant#10999]
### 重现链接

无

### Vant 版本

"^4.0.0-alpha.3"

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/29727660/187857834-8a6f8de2-c1b8-4287-9309-215a6fcc67f6.png)
![image](https://user-images.githubusercontent.com/29727660/187858024-1770c209-7f51-4b3e-b12f-0b51dae9709a.png)
用switch的时候是never 这是什么原因

### 重现步骤

![Uploading image.png…]()

**Comment by chenjiahan** [comment]
Switch 组件本身是有提供类型定义的，建议你看下项目中是否在全局正确声明了 Switch 组件的类型
