### ISSUE TITLE
[Bug Report] webstorm 显示 未知 HTML 标记 

### ISSUE THREAD

**Issue by Yacj** [vant-ui/vant#11004]
### 重现链接

无

### Vant 版本

 4.0.0-beta.1

### 描述一下你遇到的问题。

安装 最新的 4.0.0-beta.1  所以的vant组件 webstorm 无法智能提示  template 显示 未知 HTML 标记    退回 4.0.0-beta.0 无此问题

### 重现步骤

安装 4.0.0-beta.1 在ide 打开即可

**Comment by chenjiahan** [comment]
已在 4.0.0-rc.0 版本修复
