### ISSUE TITLE
[Bug Report] circle中current-rate不改变

### ISSUE THREAD

**Issue by 39499740** [vant-ui/vant#11002]
### 重现链接

无

### Vant 版本

3.6.1

### 描述一下你遇到的问题。

uniapp 中引入vant项目
vant版本3.6.1
vue版本3.2.37
circle代码如下
```
<template>
<div>
<van-circle v-model:current-rate="currentRate" :rate="30" :speed="100" :text="circleText" />
</div>
</template>
<script lang="ts" setup>
import { computed } from '@vue/reactivity';
import { ref } from 'vue';

const currentRate = ref(0);

const circleText = computed(() => {
    console.log(currentRate.value);
    return currentRate.value.toFixed(0) + '%'
})

</script>
```
进度条可以出现0到30动画，但currentRate始终为0.
当前代码在codesandbox没有任何问题，但是在我所在的环境中无法使用，已经尝试过切换vant版本，依然无效。
请问circle与uniapp是否存在兼容性问题

### 重现步骤

无

### 设备/浏览器

chrome

**Comment by chenjiahan** [comment]
vant 没有单独适配 uniapp 喔，vant 的功能只保证在 Vue 框架下可以正常使用

**Comment by 39499740** [comment]
看起来不是circle的问题，而是uniapp中computed的问题，我把computed中的代码直接写在text中就没问题了
