### ISSUE TITLE
我没有用icon组件，但是依然会出现cdn引入字体

### ISSUE THREAD

**Issue by wChenonly** [vant-ui/vant#11017]
### 重现链接

无

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

<img width="963" alt="image" src="https://user-images.githubusercontent.com/37658262/189316016-52a253f9-a70f-4e1e-8607-e3caa3eaee45.png">
打包以后的网络请求中还是出现字体

### 重现步骤

无

**Comment by chenjiahan** [comment]
1. 这个不是 CDN 请求，是 base64 内联的资源，跟 CDN 没有关系。
2. 虽然你没有直接使用 Icon 组件，但 Vant 内的很多组件都依赖了 Icon，因此 Icon 会被引入。
