### ISSUE TITLE
建议vant新增table组件

### ISSUE THREAD

**Issue by MyfollenLi95** [vant-ui/vant#11035]
### 这个功能解决了什么问题？

目前好多移动端的需求需要展示数据信息，为了客户直观明了可以利用列表的形式展现出来，方便客户查看详情

### 你期望的 API 是什么样子的？

<vant-table><vant-table/>
跟其他的组件一样可以往标签中添加属性，还有table的多选，展开等功能

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/vant-ui/vant/issues/9180
