### ISSUE TITLE
当Dialog作为组件使用时，控制台弹出警告且组件工作异常

### ISSUE THREAD

**Issue by leostou-cn** [vant-ui/vant#11036]
### 重现链接

https://gitee.com/leostou/toutiao

### Vant 版本

3.6.1

### 描述一下你遇到的问题。

环境描述：在vue3项目下，组件使用`unplugin-vue-components`自动导入，js代码使用`setup`语法糖,Dialog代码复制官网案例。
案例代码：
![image](https://user-images.githubusercontent.com/94244305/189546978-8c63e0ff-0e67-4e3f-ba0b-3a896f2f13ce.png)

bug表现：`v-model:show` 的值无论是true或者false，当当前组件渲染时都自动展示Dialog，且无法渲染插槽内容
![image](https://user-images.githubusercontent.com/94244305/189546777-b8ce6fa8-9a66-45b4-89fa-b83caf210c79.png)

控制台警告：
1. [Vue warn]: Extraneous non-props attributes (show, title, show-cancel-button) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
2. [Vue warn]: Invalid VNode type: undefined (undefined) 
![image](https://user-images.githubusercontent.com/94244305/189546860-5895f2f1-ad14-4219-8cc8-91709d1b7ed3.png)

### 重现步骤

1. 登录
2. 切换到个人
3. 点击编辑资料

### 设备/浏览器

Chrome@ 100.0.4896.127

**Comment by chenjiahan** [comment]
参见 https://github.com/vant-ui/vant/issues/10858

**Comment by leostou-cn** [comment]
> 参见 #10858

感谢！
