### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by TarekArar99** [vant-ui/vant#11043]
It seems that a problem occured on Vant website and server is returning 404 

![Screen Shot 2022-09-12 at 11 26 50 AM](https://user-images.githubusercontent.com/99167581/189596664-1e73bac4-8023-4445-98d6-f5a6580df85d.png)

**Comment by chenjiahan** [comment]
Get, I will fix it later.

**Comment by yangtoude** [comment]
The document sites on gitee and GitHub are both down:
https://vant-ui.github.io/vant/
https://vant-contrib.gitee.io/

**Comment by chenjiahan** [comment]
The site has been fixed.
