### ISSUE TITLE
[Feature Request] 新组件 Space 间距

### ISSUE THREAD

**Issue by kooriookami** [vant-ui/vant#7982]
### 这个功能解决了什么问题
设置组件之间的间距，避免组件紧贴在一起，拉开统一的空间。
我们会重复使用很多 margin 样式，这在我们的开发效率上造成了一定的困扰，间距组件可以解决这种困扰。

### 描述您想要的解决方案
新增一个 Space 组件

### 建议的API是什么样的
可以参考element-plus与antd
https://element-plus.org/#/zh-CN/component/space
https://2x.antdv.com/components/space-cn/

**Comment by icepole-jon** [comment]
有这样一个组件确实很方便，
如果要做的话，建议慎重考虑下 css `gap` 属性的兼容性，
`gap`属性在高版本浏览器才有支持，
或许可以用动态计算`margin` 或`padding` 实现

**Comment by Adaer** [comment]
我自己模仿ant vue做了一个Space组件，希望官方也出一个吧

**Comment by chenjiahan** [comment]
将在 3.6.0 版本发布 Space 组件
