### ISSUE TITLE
[Bug Report] Toast+List 滚动加载数据滚动条会弹回顶部问题

### ISSUE THREAD

**Issue by wxwebfeng** [vant-ui/vant#9815]
设备 / 浏览器
google Chrome

Vant 版本
2.12.27

Vue 版本
2.6.11

重现链接
https://jsbin.com/yivosihuho/1/edit?html,css,output

描述问题
在google 模拟移动端模式下，快速上下滚动，使用了Toast.loading 方法 就会造成滚动加载成功数据后，滚动条会弹到顶部去

**Comment by chenjiahan** [comment]
昨天在 Chrome 中复现过一次，但升级到 Chrome 95.0.4638.69 后无法再复现，你可以升级试一下

**Comment by E-10000** [comment]
的确是toast+list的问题，我这是toast+list发生的情况：
![](https://cdn.jsdelivr.net/gh/E-10000/picture/img/202201191612464.gif)
https://cdn.jsdelivr.net/gh/E-10000/picture/img/202201191612464.gif
这是只用list没有toast的情况
https://cdn.jsdelivr.net/gh/E-10000/picture/img/202201191615812.gif
![](https://cdn.jsdelivr.net/gh/E-10000/picture/img/202201191615812.gif)
吧toast去掉就可以

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/189508390-1cba6e41-70b9-4ead-a1af-047c5f9d9ea7.png)
